### ISSUE TITLE
Second Space debloating

### ISSUE THREAD

**Issue by hebasto** [Saki-EU/XiaomiADBFastbootTools#1]
Using with Second Space to debloat doesn't work as expected.
Is there any workaround to debloat the Second Space?

**Comment by Saki-EU** [comment]
Unfortunately I don't think so as Second Space is a very Xiaomi specific implementation in MIUI and I don't know much about it, especially how and where it stores data. It is possible that it creates a second copy with APK and everything but also that it uses the cache of the same app and only duplicates app data...
