### ISSUE TITLE
Debloat for Linux?

### ISSUE THREAD

**Issue by volnes** [Saki-EU/XiaomiADBFastbootTools#2]
Hi any plans for debloat tool for linux users?

**Comment by Saki-EU** [comment]
Hi,

I am contemplating making a Java version which should work on Linux as well. For now it's Windows only because C# and WinForms.

**Comment by volnes** [comment]
Thats, great!
Will wait java version...

**Comment by iTzHard** [comment]
Hello,

I am planning to make a python version for this tool soon. it should work on Linux and MacOS(I am targeting Linux atm).

**Comment by volnes** [comment]
Wow great! @iTzHard could u pm me when tool is ready?

**Comment by Saki-EU** [comment]
As far as I've been told that variant won't have a UI and it will only do some basic functionality. You'll have to wait and see for yourself 😉

**Comment by iTzHard** [comment]
Sure @volnes but you have to give me some time on that :)

**Comment by Saki-EU** [comment]
The Java version is done. This project has been renamed and will be archived soon. All future development will be done on the Java release. The new project will be available [here](https://github.com/Saki-EU/XiaomiADBFastbootTools) very soon.
